language: php
dist: bionic

php:
  - 7.4

services:
  - postgresql

addons:
  postgresql: '10'
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10

env:
  global:
    - DB=pgsql db_host='127.0.0.1' db_user=postgres db_name=cakephp_test
    - DEFAULT=1

matrix:
  fast_finish: true

  include:
    - php: 7.4
      env: COVERAGE=1

before_script:
  - if [[ $COVERAGE != 1 ]]; then phpenv config-rm xdebug.ini; fi

  - if [[ $PREFER_LOWEST != 1 ]]; then composer install --no-interaction ; fi
  - if [[ $PREFER_LOWEST == 1 ]]; then composer update --prefer-lowest --prefer-stable --no-interaction ; fi

  - if [[ $DB == 'pgsql' ]]; then psql -c 'CREATE DATABASE cakephp_test;' -U postgres; fi

script:
  - if [[ $DEFAULT == 1 ]]; then vendor/bin/phpunit; fi
  - if [[ $COVERAGE == 1 ]]; then vendor/bin/phpunit --coverage-clover=clover.xml; fi

  - if [[ $CHECKS == 1 ]]; then composer cs-check; fi

after_success:
  - if [[ $COVERAGE == 1 ]]; then bash <(curl -s https://codecov.io/bash); fi

notifications:
  email: false
