name: CakePHP PgUtils CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:

  testsuite:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php-version: [ '7.4' ]
        db-type: [ pgsql ]
    name: PHP ${{ matrix.php-version }} & ${{ matrix.db-type }}
    steps:
      - name: Setup PostgreSQL
        uses: huaxk/postgis-action@v1
        with:
          postgresql version: '11'
          postgresql password: 'postgres'
          postgresql user: 'postgres'
          postgresql db: 'cakephp_test'

      - uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: pdo_${{ matrix.db-type }}
          ini-values: apc.enable_cli = 1
          coverage: xdebug

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Get date part for cache key
        id: key-date
        run: echo "::set-output name=date::$(date +'%Y-%m')"

      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ steps.key-date.outputs.date }}-${{ hashFiles('composer.json') }}

      - name: composer install
        run: composer install

      - name: Run PHPUnit
        run: |
          export db_host=127.0.0.1 db_user=postgres db_pass=postgres db_name=cakephp_test
          vendor/bin/phpunit --coverage-clover=clover.xml

      - name: Submit code coverage
        uses: codecov/codecov-action@v1
